CREATE PROCEDURE EliminarCliente
	@Id UNIQUEIDENTIFIER	
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRANSACTION
		DELETE
		FROM            Clientes 
		WHERE        (Id = @Id)
		SELECT @Id
	COMMIT TRANSACTION
END