CREATE PROCEDURE EliminarProducto
	@Id UNIQUEIDENTIFIER	
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRANSACTION
		DELETE
		FROM            Productos
		WHERE        (Id = @Id)
		SELECT @Id
	COMMIT TRANSACTION
END